### PR TITLE
Fix SafeAreaPaddingModifier

### LINKED ISSUE #511: Bug: safeAreaPadding API not working correctly
### Description
The  API is not working correctly in OpenSwiftUI compared to SwiftUI.

### Reproduction Code
```swift
struct ContentView: View {
    var body: some View {
        Color.red
            .safeAreaPadding(.init(top: 10, leading: 20, bottom: 30, trailing: 40))
    }
}
```

### Expected Behavior
Should apply safe area padding with the specified EdgeInsets values (top: 10, leading: 20, bottom: 30, trailing: 40).

### Actual Behavior
The safe area padding is not applied correctly in OpenSwiftUI.

### Screenshots
- SwiftUI: (to be added)
- OpenSwiftUI: (to be added)

### Environment
- OpenSwiftUI version: Latest
- Platform: macOS/iOS
- Swift version: 6.1.2+

### PR DESCRIPTION
**Pull request by Dark-Existed**
Fix #511

### CODE REVIEW

**Comment by dill-lk** [comment]
hey guys i am intrested in contributing to this project .... are you guys  okay with it?

**Comment by Kyle-Ye** [comment]
> hey guys i am intrested in contributing to this project .... are you guys okay with it?

You can contribute by PR to solve some of the known issues. @dill-lk

File: Sources/OpenSwiftUICore/Layout/Modifier/InsetViewModifier.swift [hunk 1]
```diff
@@ -253,20 +253,20 @@ struct SafeAreaPaddingModifier: ViewModifier {
...
         }
     }
 
     private func insetView(edge: Edge) -> some View {
         let axis = Axis(edge: edge)
-        let inset = (insets ?? defaultPadding)[edge]
+        let inset = edges.contains(edge) ? (insets ?? defaultPadding)[edge] : 0
         return axis == .horizontal
             ? Color.clear.frame(width: inset)
             : Color.clear.frame(height: inset)
```
Comment (Kyle-Ye) [inline Sources/OpenSwiftUICore/Layout/Modifier/InsetViewModifier.swift]: This logic seems not correct too. I'll review and merge this tonight.

**Comment by dill-lk** [comment]
> > hey guys i am intrested in contributing to this project .... are you guys okay with it?
> 
> You can contribute by PR to solve some of the known issues. @dill-lk

thams broo i will start contributing
